#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=$YNH_APP_INSTANCE_NAME

# The first argument is the backup directory location for the app
# from where the script is executed and which will be compressed afterward
backup_dir=$1

# Backup sources & data
sudo cp -a "/var/www/${app}" ./sources

# Backup mysql database if needed
# db_pwd=$(sudo yunohost app setting $app mysqlpwd)
# sudo mysqldump -u $app -p$db_pwd $app > ./dump.sql

# Copy NGINX configuration
domain=$(sudo yunohost app setting "$app" domain)
sudo cp -a "/etc/nginx/conf.d/${domain}.d/${app}.conf" ./nginx.conf

# If a dedicated php-fpm process is used :
# Copy dedicated php-fpm process to backup folder
#
#sudo cp -a "/etc/php5/fpm/pool.d/${app}.conf" ./php-fpm.conf
